#!/usr/bin/env php
<?php
if (php_sapi_name() === 'cli') {
    require __DIR__ . '/vendor/autoload.php';
    # extension file
    $extensionFile = __DIR__ . '/Src/Data/extensions.json';
    $extensionArray = __DIR__ . '/Src/Data/AllExtensions.php';
    $getter    = new \Pentagonal\WhoIs\Util\DataGetter($extensionFile);
    $data      = $getter->createNewRecordExtension();
    # Check if has been regenerated
    if (is_array($data)) {
        echo "Generated : " . count($data);
    } else {
        echo "No change for data.";
    }
}
